name: Auto Reply Bot

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Auto reply to new issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🚀 ধন্যবাদ! তোমার মেসেজ পেয়ে গেছি। বট সবসময় উত্তর দিবে।"
            })
